-- =====================================================================
-- MEDLINK PMG 2026: SERVICE CATALOG, CLINICAL NORMS & COMBINATIONS MATRIX
-- Re-engineered from Delphi MedProfit Legacy System (service_groups, dct_rules)
-- =====================================================================

CREATE TABLE IF NOT EXISTS pmg_service_groups (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    parent_id TEXT,
    level INTEGER DEFAULT 1,
    description TEXT
);

CREATE TABLE IF NOT EXISTS pmg_service_catalog (
    service_code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    group_id TEXT,
    group_name TEXT,
    category TEXT NOT NULL,
    base_norm_time_minutes INTEGER DEFAULT 60,
    anesthesia_required INTEGER DEFAULT 0,
    min_stay_days INTEGER DEFAULT 0,
    max_stay_days INTEGER DEFAULT 14,
    age_min INTEGER DEFAULT 0,
    age_max INTEGER DEFAULT 120,
    gender_restriction TEXT DEFAULT 'ALL',
    package_ids TEXT,
    dsg_codes TEXT,
    base_tariff REAL DEFAULT 8735.0,
    clinical_norm_notes TEXT
);

CREATE TABLE IF NOT EXISTS pmg_service_combinations (
    id TEXT PRIMARY KEY,
    service_code TEXT NOT NULL,
    combination_name TEXT NOT NULL,
    compatible_icd_codes TEXT NOT NULL,
    mandatory_companions TEXT,
    optional_multisurg_companions TEXT,
    incompatible_services TEXT,
    allowed_doctor_positions TEXT NOT NULL,
    prohibited_doctor_positions TEXT NOT NULL,
    expected_package_number TEXT NOT NULL,
    expected_dsg_code TEXT NOT NULL,
    weight_coef REAL NOT NULL,
    calculated_tariff REAL NOT NULL,
    calculation_formula TEXT NOT NULL,
    rule_condition TEXT,
    is_library_standard INTEGER DEFAULT 1
);

-- Seed 12 Service Groups
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-01', 'SG-01', 'Хірургія органів черевної порожнини та ШКТ', NULL, 1, 'Абдомінальна хірургія: резекції кишечника, шлунка, холецистектомія, грижосічення');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-02', 'SG-02', 'Онкологічні хірургічні втручання', NULL, 1, 'Розширені та комбіновані онкохірургічні резекції пухлин з лімфодисекцією');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-03', 'SG-03', 'Офтальмологічні операції та мікрохірургія ока', NULL, 1, 'Хірургія катаракти, глаукоми, травм ока, кератопластика');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-04', 'SG-04', 'Кардіохірургія та інтервенційна кардіологія', NULL, 1, 'Стентування коронарних артерій, шунтування, корекція вад серця');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-05', 'SG-05', 'Нейрохірургія та спінальна хірургія', NULL, 1, 'Краніотомія, кліпування аневризм, декомпресія хребта, шунтування');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-06', 'SG-06', 'Травматологія, ортопедія та ендопротезування', NULL, 1, 'Остеосинтез переломів, артроскопія, ендопротезування суглобів');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-07', 'SG-07', 'Ендоскопічні діагностичні та лікувальні процедури', NULL, 1, 'Гастроскопія, колоноскопія, бронхоскопія, ендоскопічна поліпектомія');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-08', 'SG-08', 'Хіміотерапевтичне та фармакологічне введення', NULL, 1, 'Внутрішньовенна хіміотерапія, таргетна та імунотерапія онкохворих');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-09', 'SG-09', 'Променева терапія та радіологія', NULL, 1, 'Дистанційна променева терапія, брахітерапія на лінійних прискорювачах');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-10', 'SG-10', 'Реабілітаційні інтервенції та фізіотерапія', NULL, 1, 'Кінезіотерапія, ерготерапія, психологічна реабілітація за матрицями АР1-АР4');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-11', 'SG-11', 'Інтенсивна терапія, реанімація та ЕКМО', NULL, 1, 'ШВЛ >24 годин, екстракорпоральна мембранна оксигенація, плазмаферез');
INSERT OR REPLACE INTO pmg_service_groups (id, code, name, parent_id, level, description) VALUES ('grp-12', 'SG-12', 'Амбулаторні консультації та скринінги', NULL, 1, 'Спеціалізовані консультації 148 амбулаторних класів та ранній скринінг');

-- Seed Services Catalog with Norms
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('32003-00', 'Правобічна геміколектомія з анастомозом', 'grp-01', 'Хірургія органів черевної порожнини та ШКТ', 'Surgical', 180, 1, 4, 21, 18, 120, 'ALL', '4, 3', 'O0101, G01', 8735.0, 'Потребує передопераційного онкоскринінгу (колоноскопія 11600-00), обов''язкового гістологічного дослідження та посади хірурга P157. Мультихірургія дозволена з дренуванням.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('30061-02', 'Видалення поверхневого стороннього тіла з рогівки', 'grp-03', 'Офтальмологічні операції та мікрохірургія ока', 'Surgical', 30, 0, 0, 1, 0, 120, 'ALL', '47, 9, 3', 'C01, ААС', 8735.0, 'Виконується в амбулаторних умовах або стаціонарі одного дня (Пакет 47). Заборонена госпіталізація >1 доби без ускладнень.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('30518-00', 'Часткова дистальна резекція шлунка з гастроентероанастомозом', 'grp-01', 'Хірургія органів черевної порожнини та ШКТ', 'Surgical', 210, 1, 5, 25, 18, 120, 'ALL', '4, 3', 'G03, G01', 8735.0, 'Високоскладна операція. Потребує обов''язкової лімфодисекції D2 при раку шлунка (C16) та посади онкохірурга P157.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('42672-00', 'Розріз рогівки (кератотомія)', 'grp-03', 'Офтальмологічні операції та мікрохірургія ока', 'Surgical', 45, 1, 0, 2, 5, 120, 'ALL', '47, 3', 'C02, ААС', 8735.0, 'Мікрохірургічне втручання. Оплата за Пакет 47 з коефіцієнтом 0.60 при виписці в день операції.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('96199-00', 'Внутрішньовенне введення протипухлинного хіміотерапевтичного агента', 'grp-08', 'Хіміотерапевтичне та фармакологічне введення', 'Therapeutic', 120, 0, 0, 3, 0, 120, 'ALL', '18, 9', 'Пакет 18', 17865.0, 'Тарифікується за Пакетом 18 (17 865 ₴ для дорослих / 35 730 ₴ при інтенсивній терапії). Вимагає основного діагнозу Z51.1 та супутнього C00-C97.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('15269-00', 'Дистанційна променева терапія на лінійному прискорювачі (фотонна/електронна)', 'grp-09', 'Променева терапія та радіологія', 'Therapeutic', 40, 0, 0, 30, 0, 120, 'ALL', '19, 9', 'Пакет 19', 54089.0, 'Тарифікується за Пакетом 19 (54 089 ₴ - гамма / 131 499 ₴ - модульована IMRT). Обов''язкова наявність дозиметричного плану.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('11600-00', 'Діагностична та лікувальна колоноскопія з біопсією', 'grp-07', 'Ендоскопічні діагностичні та лікувальні процедури', 'Diagnostic', 45, 1, 0, 1, 40, 120, 'ALL', '13, 9, 47', 'Пакет 13, Клас 54', 1180.0, 'Пріоритетний скринінг (Пакет 13 - 1 180 ₴). При виявленні поліпів обов''язкова поліпектомія та гістологія. Посада лікаря-ендоскопіста P58.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('31548-00', 'Секторальна резекція грудної залози (мамектомія)', 'grp-02', 'Онкологічні хірургічні втручання', 'Surgical', 90, 1, 1, 7, 18, 120, 'FEMALE', '4, 47, 3', 'J01, G01', 8735.0, 'Органозберігаюча операція при пухлинах молочної залози (C50, D24). Вимагає термінового інтраопераційного гістологічного дослідження.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('90225-01', 'Екстракорпоральна мембранна оксигенація (ЕКМО, вено-артеріальна/вено-венозна)', 'grp-11', 'Інтенсивна терапія, реанімація та ЕКМО', 'Therapeutic', 1440, 1, 3, 60, 0, 120, 'ALL', '3, 4', 'A40', 177538.88, 'Найвищий коефіцієнт складності ДСГ (20.325). Базова вартість 177 538.88 ₴ (тариф 97 646.38 ₴ при K=0.55). Вимагає консиліуму реаніматологів.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('39600-00', 'Дренування внутрішньочерепної гематоми шляхом краніотомії', 'grp-05', 'Нейрохірургія та спінальна хірургія', 'Surgical', 150, 1, 5, 30, 0, 120, 'ALL', '4, 5, 3', 'B02, B02A', 8735.0, 'Ургентна нейрохірургія (інсульт з крововиливом I61 або ЧМТ S06). Ваговий коефіцієнт B02A = 11.0813 (тариф 53 237.34 ₴). Посада нейрохірурга P155.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('38218-00', 'Коронарна ангіопластика зі стентуванням (1 стент з лікарським покриттям)', 'grp-04', 'Кардіохірургія та інтервенційна кардіологія', 'Surgical', 90, 0, 2, 10, 18, 120, 'ALL', '6, 4', 'F03, Пакет 6', 44400.0, 'Тарифікується за пріоритетним Пакетом 6 (Гострий інфаркт міокарда, 44 400 - 55 200 ₴). Обов''язкова наявність ангіографа та катетеризаційної лабораторії.');
INSERT OR REPLACE INTO pmg_service_catalog (service_code, name, group_id, group_name, category, base_norm_time_minutes, anesthesia_required, min_stay_days, max_stay_days, age_min, age_max, gender_restriction, package_ids, dsg_codes, base_tariff, clinical_norm_notes) VALUES ('93125-00', 'Індивідуальне заняття з ерготерапії та відновлення побутових навичок', 'grp-10', 'Реабілітаційні інтервенції та фізіотерапія', 'Rehabilitation', 60, 0, 0, 21, 0, 120, 'ALL', '54, 53, 25', 'Пакет 54', 10820.0, 'Обов''язкова інтервенція за Пакетом 54/53. Надається ерготерапевтом (P_ERGO) у складі мультидисциплінарної команди (не менше 14 днів циклу).');

-- Seed Service Combinations Matrix
INSERT OR REPLACE INTO pmg_service_combinations (id, service_code, combination_name, compatible_icd_codes, mandatory_companions, optional_multisurg_companions, incompatible_services, allowed_doctor_positions, prohibited_doctor_positions, expected_package_number, expected_dsg_code, weight_coef, calculated_tariff, calculation_formula, rule_condition, is_library_standard) VALUES ('comb-32003-opt', '32003-00', 'Оптимальна онкохірургічна комбінація: Геміколектомія при раку ободової кишки', '[{"code": "C18.0", "name": "Злоякісне новоутворення сліпої кишки", "type": "PRIMARY"}, {"code": "C18.2", "name": "Злоякісне новоутворення висхідної ободової кишки", "type": "PRIMARY"}, {"code": "C18.3", "name": "Злоякісне новоутворення печінкового вигину ободової кишки", "type": "PRIMARY"}]', '[{"code": "30075-01", "name": "Біопсія та резекція лімфатичних вузлів брижі (лімфодисекція)"}, {"code": "30394-00", "name": "Дренування черевної порожнини"}]', '[{"code": "30440-00", "name": "Симультанна холецистектомія (+30% за мультихірургію)"}]', '[{"code": "32000-00", "name": "Обмежена резекція кишки без анастомозу (дублювання втручання)"}]', '["P157", "P158", "P58"]', '["P122", "P101", "P115"]', '4', 'O0101', 5.07, 24357.55, '8 735.00 ₴ × 5.070 × 0.55 = 24 357.55 ₴', 'Постанова № 1808, Додаток 1. Обов''язкова гістологічна верифікація та посада P157 (Хірург-онколог).', 1);
INSERT OR REPLACE INTO pmg_service_combinations (id, service_code, combination_name, compatible_icd_codes, mandatory_companions, optional_multisurg_companions, incompatible_services, allowed_doctor_positions, prohibited_doctor_positions, expected_package_number, expected_dsg_code, weight_coef, calculated_tariff, calculation_formula, rule_condition, is_library_standard) VALUES ('comb-30061-opt', '30061-02', 'Офтальмологічна амбулаторна комбінація: Травма рогівки', '[{"code": "S05.0", "name": "Травма кон''юнктиви та садно рогівки без згадки про стороннє тіло", "type": "PRIMARY"}, {"code": "T15.0", "name": "Стороннє тіло в рогівці", "type": "PRIMARY"}, {"code": "H16.0", "name": "Виразка рогівки після травматизації", "type": "PRIMARY"}]', '[]', '[{"code": "42650-00", "name": "Деепіталізація та обробка рогівки"}]', '[{"code": "42653-00", "name": "Повна наскрізна трансплантація рогівки (конфлікт обсягу)"}]', '["P145", "P146", "P58"]', '["P122", "P101"]', '47', 'ААС', 0.6, 3144.6, '8 735.00 ₴ × 0.60 × 0.60 = 3 144.60 ₴', 'Постанова № 1808, Додаток 2 (Хірургія 1 дня). Заборонена необґрунтована госпіталізація.', 1);
INSERT OR REPLACE INTO pmg_service_combinations (id, service_code, combination_name, compatible_icd_codes, mandatory_companions, optional_multisurg_companions, incompatible_services, allowed_doctor_positions, prohibited_doctor_positions, expected_package_number, expected_dsg_code, weight_coef, calculated_tariff, calculation_formula, rule_condition, is_library_standard) VALUES ('comb-30518-opt', '30518-00', 'Абдомінальна онкорезекція: Дистальна резекція шлунка', '[{"code": "C16.1", "name": "Злоякісне новоутворення дна шлунка", "type": "PRIMARY"}, {"code": "C16.3", "name": "Злоякісне новоутворення воротаря шлунка", "type": "PRIMARY"}, {"code": "K25.0", "name": "Гостра виразка шлунка з кровотечею", "type": "PRIMARY"}]', '[{"code": "30075-00", "name": "Регіонарна лімфодисекція D2"}, {"code": "30394-02", "name": "Дренування підпечінкового простору"}]', '[{"code": "30440-00", "name": "Холецистектомія"}]', '[]', '["P157", "P58"]', '["P122", "P101"]', '4', 'G03', 4.937, 23720.08, '8 735.00 ₴ × 4.937 × 0.55 = 23 720.08 ₴', 'Постанова № 1808, Додаток 1. Наказ МОЗ № 410 п. 4.1.', 1);
INSERT OR REPLACE INTO pmg_service_combinations (id, service_code, combination_name, compatible_icd_codes, mandatory_companions, optional_multisurg_companions, incompatible_services, allowed_doctor_positions, prohibited_doctor_positions, expected_package_number, expected_dsg_code, weight_coef, calculated_tariff, calculation_formula, rule_condition, is_library_standard) VALUES ('comb-96199-opt', '96199-00', 'Протипухлинний хіміотерапевтичний цикл: Рак молочної залози / ШКТ', '[{"code": "Z51.1", "name": "Сеанс хіміотерапії з приводу новоутворення (Обов''язковий основний)", "type": "PRIMARY"}, {"code": "C50.9", "name": "Злоякісне новоутворення молочної залози (Супутній)", "type": "SECONDARY"}, {"code": "C18.9", "name": "Злоякісне новоутворення ободової кишки (Супутній)", "type": "SECONDARY"}]', '[{"code": "A34009", "name": "Загальний аналіз крові розгорнутий (перед введенням хіміопрепарату)"}]', '[]', '[]', '["P156", "P157", "P58"]', '["P101"]', '18', 'Пакет 18', 1.0, 17865.0, 'Фіксований тариф Пакета 18 = 17 865.00 ₴ за цикл', 'Глава 18 Постанови № 1808. Обов''язкова комбінація діагнозу Z51.1 + C-код в ЕСОЗ.', 1);
INSERT OR REPLACE INTO pmg_service_combinations (id, service_code, combination_name, compatible_icd_codes, mandatory_companions, optional_multisurg_companions, incompatible_services, allowed_doctor_positions, prohibited_doctor_positions, expected_package_number, expected_dsg_code, weight_coef, calculated_tariff, calculation_formula, rule_condition, is_library_standard) VALUES ('comb-11600-opt', '11600-00', 'Пріоритетний скринінг: Колоноскопія пацієнтам 40+ років', '[{"code": "K63.5", "name": "Поліп ободової кишки", "type": "PRIMARY"}, {"code": "K58.0", "name": "Синдром подразненого кишечника", "type": "PRIMARY"}, {"code": "Z12.1", "name": "Спеціальне скринінгове обстеження з метою виявлення пухлин ШКТ", "type": "PRIMARY"}]', '[{"code": "30071-00", "name": "Біопсія слизової оболонки при виявленні змін"}]', '[{"code": "32075-00", "name": "Ендоскопічна поліпектомія"}]', '[]', '["P58", "P157"]', '["P122", "P101"]', '13', 'Пакет 13', 1.0, 1180.0, 'Тариф скринінгового Пакета 13 = 1 180.00 ₴', 'Глава 13 Постанови № 1808. Вік пацієнта >= 40 років. Наявність електронного направлення.', 1);
INSERT OR REPLACE INTO pmg_service_combinations (id, service_code, combination_name, compatible_icd_codes, mandatory_companions, optional_multisurg_companions, incompatible_services, allowed_doctor_positions, prohibited_doctor_positions, expected_package_number, expected_dsg_code, weight_coef, calculated_tariff, calculation_formula, rule_condition, is_library_standard) VALUES ('comb-90225-opt', '90225-01', 'Критична реанімація: Екстракорпоральна мембранна оксигенація (ЕКМО)', '[{"code": "J96.0", "name": "Гостра респіраторна недостатність важкого ступеня", "type": "PRIMARY"}, {"code": "I50.9", "name": "Серцева недостатність, кардіогенний шок", "type": "PRIMARY"}]', '[{"code": "13882-01", "name": "Безперервна допоміжна ШВЛ > 96 годин"}, {"code": "13839-00", "name": "Катетеризація центральної вени та артерії"}]', '[]', '[]', '["P154", "P157"]', '["P122", "P101"]', '3', 'A40', 20.325, 97646.38, '8 735.00 ₴ × 20.325 × 0.55 = 97 646.38 ₴', 'Додаток 1 до Постанови № 1808 (ДСГ A40). Максимальний коефіцієнт реанімації.', 1);
